---
title: Second Journal - Andrew McHale
author: Andrew McHale
date: '2018-08-28'
categories: [andrewm]
tags: []
summary: ''
---

The main focus of last week was achieving more clarity regarding the direction of the project. Prior to the group meeting on the 23rd, I had a preliminary look at the CAIGE Project Wheat datasets that we were introduced to at the last meeting (CAIGE, 2018). Much of the terminology used within the data is very technical, requiring knowledge of the domain of food production to understand.


At the meeting on Thursday the 23rd, Dr Tanaka was helpful in providing us with insight into what the important fields of the dataset were describing. This knowledge will be of great assistance as we begin to explore the data. Also, we had a group discussion about the direction of the project, deciding that we would primarily use the CAIGE wheat data as it is both accurate and detailed. We will mainly be looking at the different genotypes and the yield, analysing the relationships between these factors and various others such as weather conditions, salinity, topography, soil quality and location. We decided to divide up the different variables between us and explore the data with respect to these variables before the next meeting. This will reveal the most compelling trends, assisting us in making a decision regarding the focus of this research project.


Over the weekend, I performed some research into the analytics of food production, finding the following article: *4 ways big data analytics is disrupting the agriculture industry* (Kevin Rands, 2017). This source details the benefits of big data and analytics in agriculture, stating the main advantages as being more accurate crop predictions, stronger seed, automation of agricultural processes and increased environmental awareness. This information is useful in providing some context regarding the implications of the field we are studying.
Good progress has been made so far, with additional clarity being provided by the group meeting and discussion. Hopefully by the meeting this week we will have a clearer indication of which factors affecting crop growth that we wish to focus on so that we can begin analysing the data.


**References**  

1. CAIGE – CIMMYT Australia ICARDA Germplasm Evaluation. 2018. CAIGE – CIMMYT Australia ICARDA Germplasm Evaluation. [ONLINE] Available at: http://www.caigeproject.org.au/. [Accessed 22 August 2018].
2. Kevin Rands. 2018. 4 ways big data analytics is disrupting the agriculture industry | CIO. [ONLINE] Available at: https://www.cio.com/article/3235141/big-data/4-ways-big-data-analytics-is-disrupting-the-agriculture-industry.html. [Accessed 25 August 2018].
